''' This file is for learning purposes only. It is not intended to be used in production. '''
'''In Python, we can use the input() function to take input from the user.'''

# a=input("enter your first value:")
# b=input("enter your second value:")

# print("The value of a is:", a)
# print("The value of b is:", b)
# print("The type of a is:", type(a))
# print("The type of b is:", type(b))

# print("The sum of a and b is:", a+b)

# a=int(input("enter your first value:"))
# b=int(input("enter your second value:"))

# print("The value of a is:", a)
# print("The value of b is:", b)
# print("The type of a is:", type(a))
# print("The type of b is:", type(b))

#print("The sum of a and b is:", a+b)


# a=float(input("enter your first value:"))
# b=float(input("enter your second value:"))

# print("The value of a is:", a)
# print("The value of b is:", b)
# print("The type of a is:", type(a))
# print("The type of b is:", type(b))

# print("The sum of a and b is:", a+b)

'''The eval() function is used to evaluate a string as a Python expression. It takes a string as an argument and returns the result of the expression.'''
# a=eval(input("Enter your value 1:"))
# b=eval(input("Enter Your value 2:"))

# print(a)
# print(b)
# print(a+b)

# print(eval("10+20"))
# print(eval('0b1010'))
# print(eval('0o12'))

'''In Python, we can use the input() function to take input from the user. The input() function returns a string, so we need to convert it to the appropriate data type before using it in our program.'''
# a=int(input("Enter your first value:"))
# if a%2==0:
#     print("The value of a is even.")  
# else:
#     print("The value of a is odd.")
# print("This is the end of the program.")

'''In Python, we can use the if-elif-else statement to make decisions in our program. The if statement is used to test a condition, and if the condition is true, the code block under the if statement is executed. If the condition is false, the code block under the else statement is executed. We can also use the elif statement to test multiple conditions.'''
# marks=int(input("Enter Your marks:"))

# if marks>=60:
#     print("The student has passed with 1st Division.")
# elif marks>=50:
#     print("The student has passed with 2nd Division.")
# elif marks>=30 and marks<50:
#     print("The student has passed with 3rd Division.")
# else:
#     print("The student has failed.")   

'''In Python, we can use the operator module to perform arithmetic operations. The operator module provides a set of functions that correspond to the standard operators in Python. We can use these functions to perform arithmetic operations on numbers.'''
# import operator

# number1=float(input("Enter your first number:"))
# number2=float(input("Enter your second number:"))

# opr=input("Enter the operator (+, -, *, /):")

# if opr=='+':
#     print("The sum of", number1, "and", number2, "is:", operator.add(number1, number2)) 
# elif opr=='-':
#     print("The difference of", number1, "and", number2, "is:", operator.sub(number1, number2))
# elif opr=='*':
#     print("The product of", number1, "and", number2, "is:", operator.mul(number1, number2))
# elif opr=='/':
#     print("The quotient of", number1, "and", number2, "is:", operator.truediv(number1, number2))            
# else:
#     print("Invalid operator. Please enter a valid operator.")

'''In Python, we can use the range() function to generate a sequence of numbers. The range() function takes three arguments: start, stop, and step. The start argument is the starting point of the sequence, the stop argument is the end point of the sequence, and the step argument is the increment between each number in the sequence. If the start argument is not provided, it defaults to 0. If the step argument is not provided, it defaults to 1.  '''
# range(5) # generates a sequence of numbers from 0 to 4 
# range(1, 10) # generates a sequence of numbers from 1 to 9
# range(1, 10, 2) # generates a sequence of numbers from 1 to 9 with a step of 2
# range(10, 0, -1) # generates a sequence of numbers from 10 to 1 with a step of -1           

'''In Python, we can use the for loop to iterate over a sequence of numbers generated by the range() function. The for loop is used to execute a block of code repeatedly for a fixed number of times. The syntax of the for loop is as follows:'''

# for n in range(5):
#     print("The value of n is:", n)        

# for n in range(1, 10):
#     print("The value of n is:", n)    

# for n in range(1, 10, 2):
#     print(n)                        

# for n in range(10, 0, -1):
#     print(n)

'''In Python, we can use nested for loops to iterate over a sequence of numbers generated by the range() function. A nested for loop is a for loop that is inside another for loop. The inner for loop is executed for each iteration of the outer for loop.'''
# for table in range(2, 20):
#     print("The multiplication table of", table, "is:")
#     for n in range(1, 11):
#         print(table, "x", n, "=", table*n)
#     print()

'''In Python, we can use the break statement to exit a for loop prematurely. The break statement is used to terminate the loop when a certain condition is met. When the break statement is executed, the loop is exited immediately, and the program continues with the next statement after the loop.'''
# for n in range(1, 6):
#     if n==3:
#         continue
#     print(n)

'''In Python, we can use the continue statement to skip the current iteration of a for loop and move on to the next iteration. The continue statement is used to skip the rest of the code inside the loop for the current iteration when a certain condition is met. When the continue statement is executed, the loop continues with the next iteration, and the code after the continue statement is not executed for that iteration.'''
# for n in range(1, 6):
#     if n==3:
#         break
#     print(n)

#string indexing and string methods
'''In Python, we can use string indexing to access individual characters in a string. The index of the first character in a string is 0, the index of the second character is 1, and so on. We can also use negative indexing to access characters from the end of the string. The index of the last character in a string is -1, the index of the second last character is -2, and so on.  We can also use string methods to manipulate strings in Python. String methods are built-in functions that can be called on a string object to perform various operations on the string. Some common string methods include upper(), lower(), title(), capitalize(), and strip().
'''
string1="Welcome to Python playground programming."
# print(string1)
# print(string1.upper())
# print(string1.lower())
# print(string1.title())      
# print(string1.capitalize())
# print(string1[0])
# print(string1[11])  
'''The strip() method is used to remove any leading and trailing whitespace from a string. The replace() method is used to replace a specified substring with another substring in a string. The split() method is used to split a string into a list of substrings based on a specified delimiter. If no delimiter is specified, the default delimiter is whitespace.  '''   
# print(string1.strip())
# print(string1.replace("Python", "Java"))
# print(string1.split())  
# print(string1.split("o"))
# print(string1[-2])

# print(string1)
# print(string1[0:5])
# print(string1[6:14])
# print(string1[-10:-1])
# print(string1[1:15:2])
# '''In Python, we can use string slicing to extract a portion of a string. The syntax for string slicing is as follows: string[start:stop:step]. The start index is the index of the first character to be included in the slice, the stop index is the index of the first character to be excluded from the slice, and the step is the increment between each character in the slice. If the start index is not provided, it defaults to 0. If the stop index is not provided, it defaults to the length of the string. If the step is not provided, it defaults to 1. We can also use negative indexing in string slicing to extract characters from the end of the string.    '''
# print(string1[-1::-1])

'''In Python, we can use the len() function to get the length of a string. The len() function takes a string as an argument and returns the number of characters in the string. We can also use a for loop to iterate over each character in the string and count the number of characters manually.'''
# lenth=len(string1)
# print(lenth)
# for i in range(lenth):
#     print(string1[i],"", end="")   

'''In Python, we can use a for loop to iterate over a string in reverse order by using the range() function with negative step. The range() function takes three arguments: start, stop, and step. To iterate over a string in reverse order, we can set the start index to the last index of the string, the stop index to -1, and the step to -1. This will allow us to access each character in the string from the end to the beginning.'''
# length=len(string1)
# for n in range(length-1, -1, -1):
#     print(string1[n],"", end="")

'''In Python, we can use the augmented assignment operator (+=) to add a value to a variable and assign the result back to the variable. The augmented assignment operator is a shorthand way of writing an expression that modifies a variable. For example, instead of writing x = x + 5, we can write x += 5. This will add 5 to the current value of x and assign the result back to x.'''
# i=1
# while i<=10:
#     print(i,"Python")
#     i+=1

'''In Python, we can use the while loop to execute a block of code repeatedly as long as a certain condition is true. The syntax of the while loop is as follows: while condition: code block. The condition is evaluated before each iteration of the loop, and if the condition is true, the code block is executed. If the condition is false, the loop is terminated, and the program continues with the next statement after the loop. We can also use the break statement to exit a while loop prematurely when a certain condition is met. The continue statement can be used to skip the current iteration of the loop and move on to the next iteration when a certain condition is met.  '''
i=10
while i>=1:
    print(i,"Python")
    i-=1    